server:
  port: 9000
spring:
  application:
    name: index12306-gateway${unique-name:}-service
    #name: jav12306-gateway${unique-name:}-service 想改自己的要改前端文件
  profiles:
    #active: aggregation
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}
